### ISSUE TITLE
npm install issues

### ISSUE THREAD

**Issue by bsrdjan** [SAP/fundamental#698]
Following #691 [instructions](https://github.com/SAP/fundamental/issues/691#issuecomment-422089043), steps 1-4 work and the npm install ends with errors. Please find further details:

OS: OSX
```shel
~/s/N/fundamental ❯❯❯ python -V
Python 2.7.14
~/s/N/fundamental ❯❯❯ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
~/s/N/fundamental ❯❯❯ node -v
v10.9.0
```

The installation seem to require Python 2. I first tried with Python 3 and got following error:

```shell
> ttf2woff2@2.0.3 install /Users/d037732/src/NG-APPS/fundamental/node_modules/ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /Users/d037732/.pyenv/shims/python2 -c import platform; print(platform.python_version());
gyp ERR! stack pyenv: python2: command not found
gyp ERR! stack
gyp ERR! stack The `python2' command exists in these Python versions:
gyp ERR! stack   2.7.14
gyp ERR! stack   2.7.14/envs/py2714
gyp ERR! stack   py2714
gyp ERR! stack
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:599:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/d037732/.nvm/versions/node/v10.9.0/bin/node" "/Users/d037732/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/d037732/src/NG-APPS/fundamental/node_modules/ttf2woff2
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
```
With Python 2 and node 10, the npm install error is different:

```shell
~/s/N/fundamental ❯❯❯ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!

> fsevents@1.1.2 install /Users/d037732/src/NG-APPS/fundamental/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.9.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.9.0 (node-v64 ABI) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/d037732/.node-gyp/10.9.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/d037732/.node-gyp/10.9.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/d037732/.node-gyp/10.9.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/d037732/.node-gyp/10.9.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/d037732/.node-gyp/10.9.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/d037732/.node-gyp/10.9.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/d037732/.node-gyp/10.9.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/d037732/.node-gyp/10.9.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/d037732/.node-gyp/10.9.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/d037732/.node-gyp/10.9.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/d037732/.node-gyp/10.9.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/d037732/.node-gyp/10.9.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/d037732/.node-gyp/10.9.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/d037732/.node-gyp/10.9.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/d037732/.node-gyp/10.9.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/d037732/.node-gyp/10.9.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings and 1 error generated.
4 warnings and 1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/d037732/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/d037732/.nvm/versions/node/v10.9.0/bin/node" "/Users/d037732/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/d037732/src/NG-APPS/fundamental/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/d037732/src/NG-APPS/fundamental/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/d037732/src/NG-APPS/fundamental/node_modules/fsevents
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp make: *** [Release/obj.target/fse/fsevents.o] Error 1
ERR! not ok
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/d037732/.nvm/versions/node/v10.9.0/bin/node /Users/d037732/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/d037732/src/NG-APPS/fundamental/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/d037732/src/NG-APPS/fundamental/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/d037732/src/NG-APPS/fundamental/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
stack     at ChildProcess.onExit (/Users/d037732/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! node-pre-gypstack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
 ERR! System Darwin 17.7.0
node-pre-gyp ERR!gyp  command "/Users/d037732/.nvm/versions/node/v10.9.0/bin/node" "/Users/d037732/src/NG-APPS/fundamental/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
ERR! Systemnode-pre-gyp Darwin 17.7.0
 ERR! cwd /Users/d037732/src/NG-APPS/fundamental/node_modules/fsevents
node-pre-gyp gypERR!  ERR!node -v  v10.9.0
command "/Users/d037732/.nvm/versions/node/v10.9.0/bin/node" "/Users/d037732/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/d037732/src/NG-APPS/fundamental/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/d037732/src/NG-APPS/fundamental/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
node-pre-gyp gypERR!  node-pre-gyp -vERR! v0.6.36
 cwdnode-pre-gyp /Users/d037732/src/NG-APPS/fundamental/node_modules/fsevents
 gypERR!  not okERR!
 node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
Failed to execute '/Users/d037732/.nvm/versions/node/v10.9.0/bin/node /Users/d037732/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/d037732/src/NG-APPS/fundamental/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/d037732/src/NG-APPS/fundamental/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 16621 packages in 11.029s
found 74 vulnerabilities (27 low, 35 moderate, 12 high)
  run `npm audit fix` to fix them, or `npm audit` for details
~/s/N/fundamental ❯❯❯
```

With Python 2 and node 8, the installer complained about XCode missing on my system:

```shell
~/s/N/fundamental ❯❯❯ npm install 

> fsevents@1.1.2 install /Users/d037732/src/NG-APPS/fundamental/node_modules/fsevents
> node install

[fsevents] Success: "/Users/d037732/src/NG-APPS/fundamental/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> ttf2woff2@2.0.3 install /Users/d037732/src/NG-APPS/fundamental/node_modules/ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/Users/d037732/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/Users/d037732/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/Users/d037732/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/Users/d037732/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/d037732/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/d037732/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/Users/d037732/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/Users/d037732/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/Users/d037732/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/Users/d037732/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/Users/d037732/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/d037732/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/d037732/.nvm/versions/node/v8.11.2/bin/node" "/Users/d037732/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/d037732/src/NG-APPS/fundamental/node_modules/ttf2woff2
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> node-sass@4.9.2 install /Users/d037732/src/NG-APPS/fundamental/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.2/darwin-x64-57_binding.node
Download complete  ⸩ ⠋ :
Binary saved to /Users/d037732/src/NG-APPS/fundamental/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Caching binary to /Users/d037732/.npm/node-sass/4.9.2/darwin-x64-57_binding.node

> svgicons2svgfont@7.0.2 postinstall /Users/d037732/src/NG-APPS/fundamental/node_modules/svgicons2svgfont
> npm run metapak --silent

sh: metapak: command not found

> node-sass@4.9.2 postinstall /Users/d037732/src/NG-APPS/fundamental/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/d037732/src/NG-APPS/fundamental/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine

> gifsicle@3.0.4 postinstall /Users/d037732/src/NG-APPS/fundamental/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@3.2.0 postinstall /Users/d037732/src/NG-APPS/fundamental/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@3.1.4 postinstall /Users/d037732/src/NG-APPS/fundamental/node_modules/optipng-bin
> node lib/install.js

(node:15812) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
  ✔ optipng pre-build test passed successfully
added 1778 packages from 787 contributors in 39.218s
[!] 74 vulnerabilities found [16621 packages audited]
    Severity: 27 Low | 35 Moderate | 12 High
    Run `npm audit` for more detail
```

While waiting for XCode to install, I tried gulp and all worked fine.

README could be perhaps updated with supported platforms and prerequisites, like Python, node, ruby versions, XCode on OSX (if really needed) ...

**Comment by saadmhybris** [comment]
@bsrdjan 

I was able to trace the source of this issue and it has to do with node 10 and some of the deeper dependencies not being compatible with it. This seems to be a common problem with node10 and the solution is to use [Node LTS](https://nodejs.org/en/) (long term support) which is at v 8.12.0 right now. 

I will update our readme to include this information. along with other dependencies that you discovered. Thank for reporting these issues.
